### PR TITLE
specifications: Add a device lifecycle sub section

### PR DESCRIPTION
**Pull request by sameo**

### CODE REVIEW

**Comment by jyao1** [comment]
The flow seems good. Could we add the index to make it clear?

**Comment by sameo** [comment]
> The flow seems good. Could we add the index to make it clear?

By index you mean numbering the arrows?

**Comment by jyao1** [comment]
Numbering both the arrow and text, if possible.
As such, people can understand the relationship.

**Comment by sameo** [comment]
> Numbering both the arrow and text, if possible. As such, people can understand the relationship.

Makes sense. This should be done now.

**Review by jyao1 — APPROVED** [review]

**Pull request merged**
