### PR TITLE
[specification] PDF update

### PR DESCRIPTION
**Pull request by sameo**
Update the PDF with all recently added sections.
Add an `asciidoctor-pdf` preprocessor for it to properly render mermaid diagrams.

### CODE REVIEW

**Comment by jyao1** [comment]
I am OK with the patch.

But, CI failed? @sameo

**Review by jyao1 — APPROVED** [review]

**Comment by jyao1** [comment]
@sameo , I approved it. Once the CI issue is resolved, you can merge it.

**Comment by rpsene** [comment]
@sameo can you submit the PR again so it can run against the up to date build configuration?

**Comment by rpsene** [comment]
@sameo let me check why the build fails.

**Comment by sameo** [comment]
> @sameo can you submit the PR again so it can run against the up to date build configuration?

@rpsene Unfortunately it seems to be failing still. I'll try to run it in the new container image and see if I can reproduce this error.

**Comment by rpsene** [comment]
@sameo yes, I was following the build. I will debug it here locally now.

**Comment by rsahita** [comment]
👍  LGTM - github was giving me some issues so I could not mark it as approved

**Review by rsahita — APPROVED** [review]

**Pull request merged**
